# Generated by Django 4.0.10 on 2024-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0006_ownercharacter_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownercharacter",
            name="disabled_reason",
            field=models.TextField(default=""),
        ),
    ]
