# Generated by Django 4.2.24 on 2025-11-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0009_add_project_goal_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="show_moons_values",
            field=models.BooleanField(
                default=False,
                help_text="Displays on the pings the monthly value of the athanor/metenox. Data is populated from the moonmining/metenox applications.",
                verbose_name="Show moons values on pings",
            ),
        ),
    ]
